### PR TITLE
Lightbox fix

### PR DESCRIPTION
**Pull request by ribner**

### CODE REVIEW

**Comment by AndrewMagliozzi** [comment]
Hey Elliott, when you get a second, can you fix the conflicts between this branch and master?

**Comment by AndrewMagliozzi** [comment]
Can you also add a few details to this feature:
- [x] Email validation on form submission
- [x] A thank you template the appears after successful submission then self-closes after four seconds
- [x] [Google Analytics event tracking](https://developers.google.com/analytics/devguides/collection/analyticsjs/events)

**Comment by ribner** [comment]
I added a file called Segment.js in admithub telescope theme. This file asks for a meteor settings variable that can be stored in our settings.json file alongside the shared auth key.

**Comment by yourcelf** [comment]
This breaks Linux (including heroku) because of inconsistency between the case of filenames and the names in package.js -- check lightbox.styl.

OS X's filesystem is case insensitive, so it works there, but it will fail on any case sensitive filesystem. (I'd fixes this previously but the commits here undo my fix).

**Comment by pcorey** [comment]
I pushed a fix before deploying to stage.

**Pull request merged**
